---

- name: Adding the DataStax repository key to the trusted keys
  apt_key: 
    url: "https://debian.datastax.com/debian/repo_key"
    validate_certs: no
    state: present

- name: Adding the DataStax Community repository
  apt_repository:
    repo: '{{cassandra_apt_repo}}'
    update_cache: yes
    state: present

- name: Install Cassandra
  apt:
    name: '{{cassandra_apt_pkg}}'
    state: installed
