- name: Terminate instances
  hosts: '{{ cluster_name }}_elasticsearch_master:{{ cluster_name }}_elasticsearch_data'
  tasks:
    - name: Gather ec2 facts
      action: ec2_facts

- name: Terminate instances
  hosts: '{{ cluster_name }}_elasticsearch_master:{{ cluster_name }}_elasticsearch_data'
  connection: local
  tasks:
    - name: Terminate instances that were previously launched
      ec2:
        state: 'absent'
        instance_ids: '{{ ansible_ec2_instance_id }}'
        region: '{{ ansible_ec2_placement_region }}'
