- name: cassandra
  hosts: {{ cluster_name }}_cassandra_seeds
  become: yes
  pre_tasks: 
    - name: install the latest version of java-1.8
      yum: name=java-1.8.0-openjdk state=latest
    - name: correct java version selected
      alternatives: name=java link=/usr/bin/java path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.101-3.b13.24.amzn1.x86_64/jre/bin/java

  roles:
    - cassandra
  vars:
      dse_yum_repo: "rpm.datastax.com/enterprise"
      dse_yum_pkg: "dse-full-4.8.5-1"
      dse_yum_username: "wwilkins_expedia.com"
      dse_yum_password: "RrcPDtpIGBgiRvY"
      seed_list: |
               {% set comma = joiner(',') %}
               {% for host in groups['cassandra_txb_seeds'] -%}
                 {{ comma() }}{{ hostvars[host].ansible_default_ipv4.address}}
               {%- endfor -%}
      cassandra_main_config:
          cluster_name: 'TXB_AWS'
          num_tokens: 256
          hinted_handoff_enabled: true
          max_hint_window_in_ms: 10800000 # 3 hours
          hinted_handoff_throttle_in_kb: 1024
          max_hints_delivery_threads: 2
          batchlog_replay_throttle_in_kb: 1024
          authenticator: AllowAllAuthenticator
          authorizer: AllowAllAuthorizer
          permissions_validity_in_ms: 2000
          partitioner: org.apache.cassandra.dht.Murmur3Partitioner
          data_file_directories:
           - /data
          commitlog_directory: /datastax/commitlog
          disk_failure_policy: stop
          commit_failure_policy: stop
          key_cache_size_in_mb:
          key_cache_save_period: 14400
          row_cache_size_in_mb: 0
          row_cache_save_period: 0
          counter_cache_size_in_mb:
          counter_cache_save_period: 7200
          saved_caches_directory: /datastax/saved_caches
          commitlog_sync: periodic
          commitlog_sync_period_in_ms: 10000
          commitlog_segment_size_in_mb: 32
          concurrent_reads: 96
          concurrent_writes: 192
          concurrent_counter_writes: 96
          memtable_allocation_type: heap_buffers
          memtable_flush_writers: 6
          index_summary_capacity_in_mb:
          index_summary_resize_interval_in_minutes: 60
          trickle_fsync: false
          trickle_fsync_interval_in_kb: 10240
          storage_port: 7000
          ssl_storage_port: 7001
          start_native_transport: true
          native_transport_port: 9042
          start_rpc: true
          seed_provider:
            - class_name: org.apache.cassandra.locator.SimpleSeedProvider
              parameters:
                - seeds: " {{ seed_list }} "
          listen_address: '{{ ansible_eth0["ipv4"]["address"] }}'
          rpc_address: '{{ ansible_eth0["ipv4"]["address"] }}'
          rpc_port: 9160
          rpc_keepalive: true
          rpc_server_type: sync
          thrift_framed_transport_size_in_mb: 15
          incremental_backups: false
          snapshot_before_compaction: false
          auto_snapshot: false
          auto_bootstrap: false
          tombstone_warn_threshold: 1000
          tombstone_failure_threshold: 100000
          column_index_size_in_kb: 64
          batch_size_warn_threshold_in_kb: 64
          compaction_throughput_mb_per_sec: 0
          compaction_large_partition_warning_threshold_mb: 100
          sstable_preemptive_open_interval_in_mb: 50
          stream_throughput_outbound_megabits_per_sec: 8192
          read_request_timeout_in_ms: 5000
          range_request_timeout_in_ms: 10000
          write_request_timeout_in_ms: 2000
          counter_write_request_timeout_in_ms: 5000
          cas_contention_timeout_in_ms: 1000
          truncate_request_timeout_in_ms: 60000
          request_timeout_in_ms: 10000
          cross_node_timeout: false
          endpoint_snitch: GossipingPropertyFileSnitch
          dynamic_snitch_reset_interval_in_ms: 600000
          dynamic_snitch_update_interval_in_ms: 100
          dynamic_snitch_badness_threshold: 0.1
          request_scheduler: org.apache.cassandra.scheduler.NoScheduler
          server_encryption_options:
            internode_encryption: none
            keystore: conf/.keystore
            keystore_password: cassandra
            truststore: conf/.truststore
          client_encryption_options:
            enabled: false
            optional: false
            keystore: conf/.keystore
            keystore_password: cassandra
          internode_compression: all
          inter_dc_tcp_nodelay: false
          gc_warn_threshold_in_ms: 1000
  tasks:
        - name: Restart Cassandra
          service: name=dse state=restarted
 
